# Generated by Django 5.1.1 on 2024-10-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('modelo_revenda', models.CharField(max_length=100, verbose_name='Modelo Revenda')),
                ('modelo_sufixo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_sufixo', to='sku.sku')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('ptn', models.CharField(max_length=100, unique=True)),
                ('serie', models.CharField(max_length=100)),
                ('modelo_revenda', models.CharField(blank=True, max_length=100, verbose_name='Modelo Revenda')),
                ('responsavel_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_responsaveis', to='sku.funcionario')),
                ('modelo_sufixo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_modelo_sufixo', to='sku.sku')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_sku', to='sku.sku')),
            ],
        ),
    ]
