# Generated by Django 5.0.7 on 2024-10-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='modelo_sufixo',
        ),
        migrations.CreateModel(
            name='ModeloSufixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sufixo', models.CharField(max_length=100, verbose_name='Sufixo')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sufixos', to='sku.sku')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo_sufixo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_modelo_sufixo', to='sku.modelosufixo'),
        ),
    ]
